# Duelling D3Q(5)
python3 run.py --agt 10 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1--model_type D3Q --discriminator_nn_type RNN --write_model_dir ./deep_dialog/checkpoints/duellingdqn_rnn_5_1
python3 run.py --agt 10 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type D3Q --discriminator_nn_type RNN --write_model_dir ./deep_dialog/checkpoints/duellingdqn_rnn_5_2
python3 run.py --agt 10 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type D3Q --discriminator_nn_type RNN --write_model_dir ./deep_dialog/checkpoints/duellingdqn_rnn_5_3
# D3Q(5)
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type D3Q --discriminator_nn_type RNN --write_model_dir ./deep_dialog/checkpoints/d3q_rnn_5_1
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type D3Q --discriminator_nn_type RNN --write_model_dir ./deep_dialog/checkpoints/d3q_rnn_5_2
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type D3Q --discriminator_nn_type RNN --write_model_dir ./deep_dialog/checkpoints/d3q_rnn_5_3
# DDQ(5)
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type DDQ --write_model_dir ./deep_dialog/checkpoints/ddq_5_1
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type DDQ --write_model_dir ./deep_dialog/checkpoints/ddq_5_2
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 1 --model_type DDQ --write_model_dir ./deep_dialog/checkpoints/ddq_5_3
# DQN(1)
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_1_1
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_1_2
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_1_3
# DQN(5)
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_5_1
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_5_2
python3 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 4 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_5_3

# Prediction (Simulation)
# D3Q(5)
python2 run.py --agt 9 --usr 1 --predict_mode True --episodes 5 --run_mode 0 --act_level 1 --max_turn 40 --save_model=0 --slot_err_prob 0.00 --intent_err_prob 0.00 --trained_model_path ./deep_dialog/checkpoints/d3q_rnn_5_1/dqn.model.epoch_final.ckpt
# Our Model
python3 run.py --agt 10 --usr 1 --predict_mode True --episodes 50 --run_mode 0 --act_level 1 --max_turn 40 --save_model=0 --slot_err_prob 0.00 --intent_err_prob 0.00 --trained_model_path ./deep_dialog/checkpoints/nstep_5_2/duellingdqn.model.epoch_final.ckpt

# Prediction (Human)
python run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 1000 --episodes 300 --simulation_epoch_size 100 --write_model_dir ./deep_dialog/checkpoints/ --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --trained_model_path ./deep_dialog/checkpoints/d3q_rnn_5_1/dqn.model.epoch_final.ckpt --run_mode 3

# test
python3 run.py --agt 10 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 1000 --episodes 30 --simulation_epoch_size 100 --write_model_dir ./deep_dialog/checkpoints/ --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --model_type D3Q --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --trained_model_path ./deep_dialog/checkpoints/nstep_5_2/duellingdqn.model.epoch_final.ckpt --run_mode 0